import type { Metadata } from "next";
import "@workspace/ui/globals.css";
import "./globals.css";
import { obviouslyFont, suisseIntlFont } from "@/styles/fonts";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${obviouslyFont.variable} ${suisseIntlFont.className} font-sans antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
